// Jenkinsfile
pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_IMAGE = "kimdevspace/react-app"
        VERSION = "latest"
    }
    stages {
        stage('React Build') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('frontend') {
                    sh "docker build -t $DOCKER_IMAGE:$VERSION ."
                }
            }
        }
        stage('Docker Login & Push') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh "docker push $DOCKER_IMAGE:$VERSION"
            }
        }
        stage('Deploy') {
            steps {
                dir('frontend') {
                    sh 'chmod +x deploy.sh'
                    sh './deploy.sh'
                }
            }
        }
    }
}