pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_IMAGE = "kimdevspace/spring-boot"
        VERSION = "latest"
        PROD_CONFIG = credentials('application-prod-config')
        MAIL_CONFIG = credentials('application-mail-config')
        OAUTH_CONFIG = credentials('application-oauth-config')
    }

    stages {
        stage('Gradle Build') {
            steps {
                dir('backend') {
                    sh 'chmod +x gradlew'
                    sh '''
                        mkdir -p src/main/resources
                        cp $PROD_CONFIG src/main/resources/application-prod.yml
                        cp $MAIL_CONFIG src/main/resources/application-mail.yml
                        cp $OAUTH_CONFIG src/main/resources/application-oauth.yml
                    '''
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('backend') {
                    sh "docker build -t $DOCKER_IMAGE:$VERSION ."
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh "docker push $DOCKER_IMAGE:$VERSION"
            }
        }

        stage('Deploy') {
            steps {
                dir('backend') {
                    sh 'chmod +x deploy.sh'
                    sh './deploy.sh'
                }
            }
        }

        post {
            always {
                // 설정 파일 정리
                sh '''
                    rm -f backend/src/main/resources/application-prod.yml
                    rm -f backend/src/main/resources/application-mail.yml
                    rm -f backend/src/main/resources/application-oauth.yml
                '''
            }
    }
}